### ISSUE TITLE
Create sample database

### ISSUE THREAD

**Issue by AvinashRamachandruni** [AvinashRamachandruni/avni-etl#1]
Sync_telemetry (10k)
Program_enrolment (10k)
Program encounter (100k)
Encounter (100k)
Users (10)
Individuals (10k)

**Comment by vinayvenu** [comment]
@ak2502 everything good here?

**Comment by ak2502** [comment]
Link to database

https://drive.google.com/file/d/1MTfZMdqNir7rVpaNuTCBH1lQ7g6yv9-R/view?usp=drive_link
